cabal-version:      3.0
name:               hcurl
version:            0.1.0.0
synopsis:           Network client based on curl multi interface
description:
  Please see the README on GitHub at <https://github.com/Reykudo/hcurl#readme>

category:           Web
homepage:           https://github.com/Reykudo/hcurl#readme
bug-reports:        https://github.com/Reykudo/hcurl/issues
author:             Diamondy4
maintainer:         diamondy4@hotmail.com
copyright:          2022 Diamondy4
license:            Apache-2.0
build-type:         Simple
extra-doc-files:
  ChangeLog.md
  README.md

extra-source-files:
  third-party/include/waitfree-mpsc-queue/LICENSE
  third-party/include/waitfree-mpsc-queue/README.md
  third-party/include/waitfree-mpsc-queue/UPSTREAM

source-repository head
  type:     git
  location: https://github.com/Reykudo/hcurl

flag no-pkg-config
  description: Don't use pkg-config to check C library dependencies.
  default:     False
  manual:      True

common warnings
  ghc-options:
    -Wall -Wno-unticked-promoted-constructors -Wmissing-methods
    -Wunused-packages -Werror=missing-methods
    -Werror=incomplete-patterns

common extensions
  default-extensions:
    BlockArguments
    DataKinds
    DefaultSignatures
    DeriveAnyClass
    DerivingStrategies
    DerivingVia
    DuplicateRecordFields
    FunctionalDependencies
    GADTs
    ImpredicativeTypes
    LambdaCase
    MultiWayIf
    NoCUSKs
    NoNamedWildCards
    NoStarIsType
    OverloadedRecordDot
    OverloadedStrings
    PartialTypeSignatures
    PatternSynonyms
    StrictData
    TypeFamilies
    UndecidableInstances
    ViewPatterns

  default-language:   GHC2021

library
  import:             warnings, extensions

  -- cabal-fmt: expand src
  exposed-modules:
    HCurl.Agent
    HCurl.Extras
    HCurl.Internal.Body
    HCurl.Internal.Callbacks
    HCurl.Internal.Easy
    HCurl.Internal.Headers
    HCurl.Internal.Metrics
    HCurl.Internal.MPSC
    HCurl.Internal.Multi
    HCurl.Internal.Options
    HCurl.Internal.Options.Class
    HCurl.Internal.Options.TH
    HCurl.Internal.Raw
    HCurl.Internal.Raw.Alloc
    HCurl.Internal.Raw.Context
    HCurl.Internal.Raw.Curl
    HCurl.Internal.Raw.CurlFunctions
    HCurl.Internal.Raw.Extras
    HCurl.Internal.Raw.Headers
    HCurl.Internal.Raw.Metrics
    HCurl.Internal.Raw.MPSC
    HCurl.Internal.Raw.SimpleString
    HCurl.Internal.Raw.UV
    HCurl.Internal.Response
    HCurl.Internal.Slist
    HCurl.PyFCustom
    HCurl.Request
    HCurl.Response
    HCurl.Simple
    HCurl.Streaming
    HCurl.Types

  autogen-modules:    Paths_hcurl
  other-modules:      Paths_hcurl
  hs-source-dirs:     src
  include-dirs:       cbits third-party
  install-includes:
    curl_metrics.h
    curl_uv.h
    extras.h
    headers.h
    include/waitfree-mpsc-queue/mpscq.h
    message_chan.h
    simple_string.h

  c-sources:
    cbits/curl_metrics.c
    cbits/curl_uv.c
    cbits/extras.c
    cbits/headers.c
    cbits/message_chan.c
    cbits/simple_string.c
    third-party/include/waitfree-mpsc-queue/mpsc.c

  cc-options:         -std=gnu18 -Wall -Wextra

  if flag(no-pkg-config)
    extra-libraries:
      curl
      uv

  else
    pkgconfig-depends: libcurl, libuv

  build-tool-depends: c2hs:c2hs >=0.28.8 && <0.29
  build-depends:
    , async             >=2.2.6    && <2.3
    , base              >=4.20.2   && <5
    , bytestring        >=0.12.2   && <0.13
    , case-insensitive  >=1.2.1    && <1.3
    , containers        >=0.7      && <0.9
    , deepseq           >=1.5      && <1.7
    , http-types        >=0.12.4   && <0.13
    , inline-c          >=0.9.1.10 && <0.10
    , mtl               >=2.3.1    && <2.4
    , PyF               >=0.11.5   && <0.12
    , resourcet         >=1.3      && <1.4
    , roundRobin        >=0.1.2    && <0.2
    , singletons        >=3.0.4    && <3.1
    , singletons-th     >=3.4      && <3.6
    , stm               >=2.5.3    && <2.6
    , template-haskell  >=2.22     && <2.25
    , unliftio          >=0.2.25.1 && <0.3

test-suite hcurl-test
  import:          warnings, extensions
  type:            exitcode-stdio-1.0
  main-is:         Spec.hs
  autogen-modules: Paths_hcurl
  other-modules:   Paths_hcurl
  hs-source-dirs:  test
  ghc-options:
    -Wall -Wincomplete-patterns -Wno-type-defaults
    -Wno-unticked-promoted-constructors -threaded -rtsopts
    -with-rtsopts=-N

  build-depends:
    , async       >=2.2.6  && <2.3
    , base        >=4.20.2 && <5
    , bytestring  >=0.12.2 && <0.13
    , hcurl
    , network     >=3.2    && <3.3
    , resourcet   >=1.3    && <1.4

executable hcurl-example
  import:          warnings, extensions
  main-is:         Main.hs
  autogen-modules: Paths_hcurl
  other-modules:   Paths_hcurl
  hs-source-dirs:  examples
  ghc-options:
    -Wall -Wincomplete-patterns -Wno-type-defaults
    -Wno-unticked-promoted-constructors -threaded -rtsopts
    -with-rtsopts=-N

  build-depends:
    , base       >=4.20.2 && <5
    , hcurl
    , resourcet  >=1.3    && <1.4

benchmark hcurl-benchmark
  import:          warnings, extensions
  type:            exitcode-stdio-1.0
  main-is:         Main.hs
  autogen-modules: Paths_hcurl
  other-modules:   Paths_hcurl
  hs-source-dirs:  benchmark
  ghc-options:
    -Wall -Wincomplete-patterns -Wno-type-defaults
    -Wno-unticked-promoted-constructors -threaded -rtsopts
    -with-rtsopts=-N

  build-depends:
    , async           >=2.2.6    && <2.3
    , atomic-primops  >=0.8.8    && <0.9
    , base            >=4.20.2   && <5
    , bytestring      >=0.12.2   && <0.13
    , criterion       >=1.6.4    && <1.7
    , deepseq         >=1.5      && <1.7
    , hcurl
    , http-client     >=0.7.19   && <0.8
    , http-conduit    >=2.3.9.1  && <2.4
    , PyF             >=0.11.5   && <0.12
    , resourcet       >=1.3      && <1.4
    , unliftio        >=0.2.25.1 && <0.3
